
import java.awt.BorderLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author AS
 */
public class DecryptionX extends javax.swing.JFrame {

    /**
     * Creates new form DecryptionX
     */
    public DecryptionX() {
        initComponents();
        InitForm(false);
    }

    /*Var for list*/
    private final DefaultListModel item = new DefaultListModel();
    private final String wordAt[] = new String[256];

    /*Add to list*/
    private void addListItem(int i, String word) {
        item.addElement((i + 1) + ". " + word);
        wordAt[i] = word;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCipher = new javax.swing.ButtonGroup();
        jTextFieldPathFile = new javax.swing.JTextField();
        jButtonOpen = new javax.swing.JButton();
        jLabelFile = new javax.swing.JLabel();
        jScrollPaneShow = new javax.swing.JScrollPane();
        jTextPaneShow = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonCaesarCipher = new javax.swing.JRadioButton();
        jRadioButtonVigenereCipher = new javax.swing.JRadioButton();
        jButtonDecryptFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneShowKey = new javax.swing.JTextPane();
        jTextFieldPathFileKey = new javax.swing.JTextField();
        jButtonOpenKey = new javax.swing.JButton();
        jLabelFile1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DecryptionX");

        jButtonOpen.setText("Open");
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });

        jLabelFile.setText("File");

        jScrollPaneShow.setViewportView(jTextPaneShow);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel1.setText("Encrypt file");

        buttonGroupCipher.add(jRadioButtonCaesarCipher);
        jRadioButtonCaesarCipher.setSelected(true);
        jRadioButtonCaesarCipher.setText("Caesar cipher");
        jRadioButtonCaesarCipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCaesarCipherActionPerformed(evt);
            }
        });

        buttonGroupCipher.add(jRadioButtonVigenereCipher);
        jRadioButtonVigenereCipher.setText("Vigenere cipher");
        jRadioButtonVigenereCipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVigenereCipherActionPerformed(evt);
            }
        });

        jButtonDecryptFile.setText("Decrypt");
        jButtonDecryptFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecryptFileActionPerformed(evt);
            }
        });

        jList1.setModel(item);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jScrollPane3.setViewportView(jTextPaneShowKey);

        jButtonOpenKey.setText("Open");
        jButtonOpenKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenKeyActionPerformed(evt);
            }
        });

        jLabelFile1.setText("Key");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText("Key file");

        jMenuFile.setText("File");

        jMenuItem1.setText("About me");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItem1);

        jMenuItem2.setText("Eixt");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItem2);

        jMenuBar1.add(jMenuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDecryptFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFile)
                            .addComponent(jLabelFile1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonCaesarCipher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonVigenereCipher)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldPathFileKey, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPathFile, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonOpenKey, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneShow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPathFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpen)
                    .addComponent(jLabelFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPathFileKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOpenKey)
                    .addComponent(jLabelFile1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCaesarCipher)
                    .addComponent(jRadioButtonVigenereCipher))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPaneShow, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDecryptFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Open Encrypt file*/
    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed
        JFileChooser fileopen = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("Text/CSV file", "txt", "csv");
        fileopen.addChoosableFileFilter(filter);
        int ret = fileopen.showDialog(null, "Choose file");
        if (ret == JFileChooser.APPROVE_OPTION) {
            jTextPaneShow.setText(null);
            File file = fileopen.getSelectedFile();
            String str = "";
            try {
                FileInputStream in = new FileInputStream(file);
                int c;
                while ((c = in.read()) != -1) {
                    str = str + (char) c;
                }
                in.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            // Show Path Name
            jTextFieldPathFile.setText(fileopen.getSelectedFile().toString());
            jTextPaneShow.setText(str);
        }
    }//GEN-LAST:event_jButtonOpenActionPerformed

    /*Decrypt File*/
    private void jButtonDecryptFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecryptFileActionPerformed
        item.clear();
        String cipherWord = null;
        if (jRadioButtonCaesarCipher.isSelected()) {
            //Brute Force (1-256)
            for (int i = 0; i < 256; i++) {
                cipherWord = new Cipher().CaesarCipher((i + 1), jTextPaneShow.getText());
                addListItem(i, cipherWord);
            }
        } else if (jRadioButtonVigenereCipher.isSelected()) {
            //
            cipherWord = new Cipher().VigenereCipher(jTextPaneShowKey.getText(), jTextPaneShow.getText());
            addListItem(0, cipherWord);
        } else {
            JOptionPane.showMessageDialog(null, "!!!Please select scope!!!");
        }
    }//GEN-LAST:event_jButtonDecryptFileActionPerformed

    /*Select to show*/
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (evt.getClickCount() == 2) {
            //call result frame
            GetSetResult result = new GetSetResult();
            result.setResult(wordAt[jList1.getSelectedIndex()]);
            ResultFrame displayPanelResult = new ResultFrame();
            JFrame displayFrameResult = new JFrame("DecryptionX");
            displayFrameResult.getContentPane().add(displayPanelResult, BorderLayout.CENTER);              
            displayFrameResult.pack();
            displayFrameResult.setVisible(true);
        }
    }//GEN-LAST:event_jList1MouseClicked

    /*Open Key file*/
    private void jButtonOpenKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenKeyActionPerformed
        JFileChooser fileopen = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("Text/CSV file", "txt", "csv");
        fileopen.addChoosableFileFilter(filter);
        int ret = fileopen.showDialog(null, "Choose file");
        if (ret == JFileChooser.APPROVE_OPTION) {
            jTextPaneShowKey.setText(null);
            File file = fileopen.getSelectedFile();
            String str = "";
            try {
                FileInputStream in = new FileInputStream(file);
                int c;
                while ((c = in.read()) != -1) {
                    str = str + (char) c;
                }
                in.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            // Path Name
            jTextFieldPathFileKey.setText(fileopen.getSelectedFile().toString());
            jTextPaneShowKey.setText(str);
        }
    }//GEN-LAST:event_jButtonOpenKeyActionPerformed

    /*change mode and enabled form(Vigenere cipher)*/
    private void jRadioButtonVigenereCipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVigenereCipherActionPerformed
        InitForm(true);
    }//GEN-LAST:event_jRadioButtonVigenereCipherActionPerformed

    /*change mode and enabled form(Caesar cipher)*/
    private void jRadioButtonCaesarCipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCaesarCipherActionPerformed
        InitForm(false);
    }//GEN-LAST:event_jRadioButtonCaesarCipherActionPerformed

    /*Enabled form*/
    private void InitForm(boolean status) {
        jLabelFile1.setEnabled(status);
        jTextFieldPathFileKey.setEnabled(status);
        jButtonOpenKey.setEnabled(status);
        jLabel2.setEnabled(status);
        jTextPaneShowKey.setEnabled(status);
    }
    
    /*About me*/
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "DecryptionX v.1.0\nProduct by \n51141281 Mr. Salahuddin Benno\n51160844 Mr. Zulkiflee Hulu\nComputer Engineering, Walailak University\n");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /*Exit*/
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DecryptionX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCipher;
    private javax.swing.JButton jButtonDecryptFile;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtonOpenKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JLabel jLabelFile1;
    private javax.swing.JList jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButtonCaesarCipher;
    private javax.swing.JRadioButton jRadioButtonVigenereCipher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneShow;
    private javax.swing.JTextField jTextFieldPathFile;
    private javax.swing.JTextField jTextFieldPathFileKey;
    private javax.swing.JTextPane jTextPaneShow;
    private javax.swing.JTextPane jTextPaneShowKey;
    // End of variables declaration//GEN-END:variables
}
